services:

  backend:
    image: ghcr.io/ashvortex404/citycare24-backend:latest
    container_name: citycare-backend
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: ghcr.io/ashvortex404/citycare24-frontend:latest
    container_name: citycare-frontend
    ports:
      - "80:80"
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
