apiVersion: v1
kind: Service
metadata:
  name: civicwatch-frontend
  namespace: civicwatch
  labels:
    app.kubernetes.io/name: civicwatch
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app: civicwatch-frontend
